Repository OpenDataforWeb3/Resources, pull requests merged in 2023-01, with the labels that each got.

#52 move files to match new sitemap
  README.md
  blog/README.md
  docs/data-dictionary.md
  docs/faq.md
  docs/glossary.md
  docs/landscape.md
  docs/resources.md
  profile/README.md
Labels: community presence

#64 Updated Ocean README url
  docs/faq.md
Labels: documentation

#83 update readme front page website
  README.md
Labels: documentation

#85 Update to contribution doc
  .DS_Store
  CONTRIBUTING.md
Labels: documentation

#82 v1 get involved
  docs/Get-Involved.md
Labels: documentation

#88 Gray-patch01
  docs/glossary.md
Labels: documentation

#87 Fix misspelling
  docs/Get-Involved.md
Labels: bug, documentation

#94 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#86 Updated ReadMe
  README.md
Labels: documentation

#72 First draft of FAQ #65
  docs/faq.md
  sybil-image.png
Labels: documentation

#79 Create Streams-to-Podcasts.md
  .github/ops/Streams-to-Podcasts.md
Labels: documentation

#90 Cr patch4 - add contribution to readme
  README.md
Labels: documentation
